server.port=${PORT:8080}
spring.application.name=grocery-backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/grocery_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:rootdatabase@123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey}
jwt.expiration=${JWT_EXPIRATION:86400000}

razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_Sm2LEU5vnT9Dqb}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:OrQu6V7aXd7q4p8CyUVTz3b4}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:rathodchetan787878@gmail.com}
spring.mail.password=${MAIL_PASSWORD:cgowfgafbzbaaeiq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:demo}
cloudinary.api-key=${CLOUDINARY_API_KEY:demo}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:demo}

app.frontend-url=${FRONTEND_URL:http://localhost:5173}
springdoc.swagger-ui.path=/swagger-ui.html
